// Daily rotating quote — deterministic (same day → same quote for everyone).
// Focused on study, discipline, growth, engineering.

export const QUOTES = [
  { q: "The expert in anything was once a beginner.", a: "Helen Hayes" },
  { q: "Discipline is choosing between what you want now and what you want most.", a: "Abraham Lincoln" },
  { q: "It always seems impossible until it\'s done.", a: "Nelson Mandela" },
  { q: "Success is the sum of small efforts, repeated day in and day out.", a: "Robert Collier" },
  { q: "Don\'t watch the clock; do what it does. Keep going.", a: "Sam Levenson" },
  { q: "A year from now you may wish you had started today.", a: "Karen Lamb" },
  { q: "Hard work beats talent when talent doesn\'t work hard.", a: "Tim Notke" },
  { q: "Amateurs sit and wait for inspiration. The rest of us just get up and go to work.", a: "Stephen King" },
  { q: "You don\'t rise to the level of your goals. You fall to the level of your systems.", a: "James Clear" },
  { q: "Motivation gets you going. Discipline keeps you growing.", a: "John C. Maxwell" },
  { q: "Continuous improvement is better than delayed perfection.", a: "Mark Twain" },
  { q: "The best way to predict the future is to invent it.", a: "Alan Kay" },
  { q: "Programs must be written for people to read, and only incidentally for machines to execute.", a: "Harold Abelson" },
  { q: "First, solve the problem. Then, write the code.", a: "John Johnson" },
  { q: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", a: "Martin Fowler" },
  { q: "Simplicity is the soul of efficiency.", a: "Austin Freeman" },
  { q: "The scariest moment is always just before you start.", a: "Stephen King" },
  { q: "You do not rise to the occasion; you fall to the level of your preparation.", a: "Archilochus" },
  { q: "Compound interest is the eighth wonder of the world. He who understands it, earns it.", a: "Albert Einstein" },
  { q: "It does not matter how slowly you go as long as you do not stop.", a: "Confucius" },
  { q: "What you do every day matters more than what you do once in a while.", a: "Gretchen Rubin" },
  { q: "The magic you\'re looking for is in the work you\'re avoiding.", a: "Unknown" },
  { q: "Fall in love with the process and the results will come.", a: "Eric Thomas" },
  { q: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
  { q: "Small daily improvements are the key to staggering long-term results.", a: "Robin Sharma" },
  { q: "You are what you repeatedly do. Excellence is not an act but a habit.", a: "Aristotle" },
  { q: "The two most powerful warriors are patience and time.", a: "Leo Tolstoy" },
  { q: "The best time to plant a tree was 20 years ago. The second best time is now.", a: "Chinese Proverb" },
  { q: "If you don\'t sacrifice for what you want, what you want becomes the sacrifice.", a: "Unknown" },
  { q: "Nothing worth having comes easy.", a: "Theodore Roosevelt" },
  { q: "Focus on being productive, not busy.", a: "Tim Ferriss" },
  { q: "Study while others are sleeping; work while others are loafing.", a: "William Arthur Ward" },
  { q: "One percent better every day. That\'s the whole game.", a: "James Clear" },
  { q: "Don\'t count the days. Make the days count.", a: "Muhammad Ali" },
  { q: "Persistence is not a long race; it is many short races one after another.", a: "Walter Elliot" },
  { q: "The pain of discipline is far less than the pain of regret.", a: "Sarah Bombell" },
  { q: "Everything you\'ve ever wanted is on the other side of fear.", a: "George Addair" },
  { q: "Great things are done by a series of small things brought together.", a: "Vincent Van Gogh" },
  { q: "The only person you are destined to become is the person you decide to be.", a: "Ralph Waldo Emerson" },
  { q: "Wake up with determination. Go to bed with satisfaction.", a: "George Lorimer" },
  { q: "Learning never exhausts the mind.", a: "Leonardo da Vinci" },
  { q: "There are no shortcuts to any place worth going.", a: "Beverly Sills" },
  { q: "If you can\'t explain it simply, you don\'t understand it well enough.", a: "Richard Feynman" },
  { q: "First learn, then remove.", a: "Ancient wisdom" },
  { q: "You miss 100% of the shots you don\'t take.", a: "Wayne Gretzky" },
  { q: "Direction is more important than speed.", a: "Richard L. Evans" },
  { q: "The way to get started is to quit talking and begin doing.", a: "Walt Disney" },
  { q: "Your limitation—it\'s only your imagination.", a: "Unknown" },
  { q: "Push yourself, because no one else is going to do it for you.", a: "Unknown" },
  { q: "Great things never come from comfort zones.", a: "Unknown" },
  { q: "Dream it. Wish it. Do it.", a: "Unknown" },
  { q: "Success doesn\'t just find you. You have to go out and get it.", a: "Unknown" },
  { q: "The harder you work for something, the greater you\'ll feel when you achieve it.", a: "Unknown" },
  { q: "Dream bigger. Do bigger.", a: "Unknown" },
  { q: "Don\'t stop when you\'re tired. Stop when you\'re done.", a: "Wesley Snipes" },
  { q: "Wake up with determination. Go to bed with satisfaction.", a: "George Lorimer" },
  { q: "Do something today that your future self will thank you for.", a: "Sean Patrick Flanery" },
  { q: "Little things make big days.", a: "Unknown" },
  { q: "It\'s going to be hard, but hard does not mean impossible.", a: "Unknown" },
  { q: "Don\'t wait for opportunity. Create it.", a: "Unknown" },
  { q: "The key to success is to focus on goals, not obstacles.", a: "Unknown" },
  { q: "Dream it. Believe it. Build it.", a: "Unknown" },
  { q: "The only limit to our realization of tomorrow is our doubts of today.", a: "Franklin D. Roosevelt" },
  { q: "Do what you can, with what you have, where you are.", a: "Theodore Roosevelt" },
  { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt" },
  { q: "Whether you think you can or you think you can\'t, you\'re right.", a: "Henry Ford" },
  { q: "The only way out is through.", a: "Robert Frost" },
  { q: "If it doesn\'t challenge you, it doesn\'t change you.", a: "Fred DeVito" },
  { q: "The comfort zone is a beautiful place, but nothing ever grows there.", a: "Unknown" },
  { q: "Doubt kills more dreams than failure ever will.", a: "Suzy Kassem" },
  { q: "The best revenge is massive success.", a: "Frank Sinatra" },
  { q: "You don\'t have to be great to start, but you have to start to be great.", a: "Zig Ziglar" },
  { q: "Setting goals is the first step in turning the invisible into the visible.", a: "Tony Robbins" },
  { q: "If you want to achieve greatness stop asking for permission.", a: "Unknown" },
  { q: "Things work out best for those who make the best of how things work out.", a: "John Wooden" },
  { q: "To live a creative life, we must lose our fear of being wrong.", a: "Anonymous" },
  { q: "Innovation distinguishes between a leader and a follower.", a: "Steve Jobs" },
  { q: "Stay hungry, stay foolish.", a: "Steve Jobs" },
  { q: "Life is what happens when you\'re busy making other plans.", a: "John Lennon" },
  { q: "Get busy living or get busy dying.", a: "Stephen King" },
  { q: "You have within you right now, everything you need to deal with whatever the world can throw at you.", a: "Brian Tracy" },
  { q: "You become what you believe.", a: "Oprah Winfrey" },
  { q: "Believe you can and you\'re halfway there.", a: "Theodore Roosevelt" },
  { q: "Fake it until you make it.", a: "Unknown" },
  { q: "Life shrinks or expands in proportion to one\'s courage.", a: "Anais Nin" },
  { q: "Everything you can imagine is real.", a: "Pablo Picasso" },
  { q: "What we think, we become.", a: "Buddha" },
  { q: "An unexamined life is not worth living.", a: "Socrates" },
  { q: "Turn your wounds into wisdom.", a: "Oprah Winfrey" },
  { q: "Time is what we want most, but what we use worst.", a: "William Penn" },
  { q: "Simplicity is the ultimate sophistication.", a: "Leonardo da Vinci" },
  { q: "Life is really simple, but we insist on making it complicated.", a: "Confucius" },
  { q: "May you live all the days of your life.", a: "Jonathan Swift" },
  { q: "It is never too late to be what you might have been.", a: "George Eliot" },
  { q: "Life is either a daring adventure or nothing at all.", a: "Helen Keller" },
  { q: "The only impossible journey is the one you never begin.", a: "Tony Robbins" },
  { q: "Only I can change my life. No one can do it for me.", a: "Carol Burnett" },
  { q: "Do one thing every day that scares you.", a: "Eleanor Roosevelt" },
  { q: "The healthiest response to life is joy.", a: "Deepak Chopra" },
  { q: "If you have a dream, don\'t just sit there. Gather courage to believe that you can succeed.", a: "Roopleen" },
  { q: "Life is not a problem to be solved, but a reality to be experienced.", a: "Soren Kierkegaard" },
  { q: "If life were predictable it would cease to be life, and be without flavor.", a: "Eleanor Roosevelt" },
  { q: "Live for today because yesterday is gone and tomorrow may never come.", a: "Unknown" },
  { q: "The best preparation for tomorrow is doing your best today.", a: "H. Jackson Brown Jr." },
  { q: "Nothing is impossible, the word itself says I\'m possible!", a: "Audrey Hepburn" },
  { q: "Change your thoughts and you change your world.", a: "Norman Vincent Peale" },
  { q: "Learn as if you will live forever. Live like you will die tomorrow.", a: "Mahatma Gandhi" },
  { q: "The mind is everything. What you think you become.", a: "Buddha" },
  { q: "Strive not to be a success, but rather to be of value.", a: "Albert Einstein" },
  { q: "Try to be a rainbow in someone\'s cloud.", a: "Maya Angelou" },
  { q: "What\'s coming will come, and we\'ll meet it when it does.", a: "J.K. Rowling" },
  { q: "Sometimes later becomes never. Do it now.", a: "Unknown" },
  { q: "Nothing worth having comes easy.", a: "Theodore Roosevelt" },
  { q: "What you get by achieving your goals is not as important as what you become by achieving your goals.", a: "Zig Ziglar" },
  { q: "You are enough just as you are.", a: "Meghan Markle" },
  { q: "Be the change that you wish to see in the world.", a: "Mahatma Gandhi" },
  { q: "The purpose of our lives is to be happy.", a: "Dalai Lama" },
  { q: "Never let the fear of striking out keep you from playing the game.", a: "Babe Ruth" },
  { q: "Only put off until tomorrow what you are willing to die having left undone.", a: "Pablo Picasso" },
  { q: "If you look at what you have in life, you\'ll always have more.", a: "Oprah Winfrey" },
  { q: "Nothing will work unless you do.", a: "Maya Angelou" },
  { q: "A journey of a thousand miles begins with a single step.", a: "Lao Tzu" },
  { q: "What you seek is seeking you.", a: "Rumi" },
  { q: "Your time is limited, so don\'t waste it living someone else\'s life.", a: "Steve Jobs" },
  { q: "Whatever you can do, or dream you can, begin it. Boldness has genius, power, and magic in it.", a: "Goethe" },
  { q: "Everything has beauty, but not everyone can see.", a: "Confucius" },
  { q: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", a: "Anne Frank" },
  { q: "Well done is better than well said.", a: "Benjamin Franklin" },
  { q: "The bad news is time flies. The good news is you\'re the pilot.", a: "Michael Altshuler" },
  { q: "Winners are not people who never fail, but people who never quit.", a: "Unknown" },
  { q: "If you want to lift yourself up, lift up someone else.", a: "Booker T. Washington" },
  { q: "The two most important days in your life are the day you are born and the day you find out why.", a: "Mark Twain" },
  { q: "Formal education will make you a living; self-education will make you a fortune.", a: "Jim Rohn" },
  { q: "Whether it\'s the best of times or the worst of times, it\'s the only time we\'ve got.", a: "Art Buchwald" },
  { q: "Nothing is worth more than this day.", a: "Johann Wolfgang von Goethe" },
  { q: "If you\'re going through hell, keep going.", a: "Winston Churchill" },
  { q: "The most difficult thing is the decision to act, the rest is merely tenacity.", a: "Amelia Earhart" },
  { q: "Every strike brings me closer to the next home run.", a: "Babe Ruth" },
  { q: "Definiteness of purpose is the starting point of all achievement.", a: "W. Clement Stone" },
  { q: "Success is not in what you have, but who you are.", a: "Bo Bennett" },
  { q: "The road to success and the road to failure are almost exactly the same.", a: "Colin R. Davis" },
  { q: "Opportunities don\'t happen. You create them.", a: "Chris Grosser" },
  { q: "Try not to become a person of success, but rather try to become a person of value.", a: "Albert Einstein" },
  { q: "All progress takes place outside the comfort zone.", a: "Michael John Bobak" },
  { q: "You may only succeed if you desire succeeding; you may only fail if you do not mind failing.", a: "Philippos" },
  { q: "Courage is one step ahead of fear.", a: "Coleman Young" },
  { q: "Successful people do what unsuccessful people are not willing to do.", a: "Jeff Olson" },
  { q: "Success usually comes to those who are too busy to be looking for it.", a: "Henry David Thoreau" },
]

export function quoteForToday(iso) {
  // deterministic per day
  const d = iso || new Date().toISOString().slice(0, 10)
  let h = 0
  for (let i = 0; i < d.length; i++) h = (h * 31 + d.charCodeAt(i)) >>> 0
  return QUOTES[h % QUOTES.length]
}
